services:
  - name: refbot-webapp
    type: web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 21
      - key: SKIP_INSTALL_DEPS
        value: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
